version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: django_app
    ports:
      - "4141:8000"
    depends_on:
      - db
    environment:
      DJANGO_DEBUG: 'True'
      SSO_CLIENT_ID: 123456789fibr
      SSO_CLIENT_SECRET: Mh7KiMJgCNnFwamDTnpyS6V0Dyck1J03
      SSO_REDIRECT_URI: https://appd.4tz.web.id/callback
      SSO_BASE_URI: https://sso.4tz.web.id
      SSO_REALM_MASTER: master
      HDFS_URL: "http://localhost:5001/"
      DASHBOARD_URL: 'http://34.128.121.103:5000/dashboard/list/'
      DATA_MODELER_URL: 'http://34.128.103.189:8000/data-modeler/'
      DATA_PROCESSOR_URL: 'http://34.128.103.189/#/pds/dataprocessing'
      STARROCKS_URL: "http://localhost:5002/"
      AIRFLOW_URL: "http://localhost::5003/"

volumes:
  postgres_data:
