version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_DEBUG: 'True'
      HDFS_URL: "#"
      DASHBOARD_URL: '#'
      DATA_MODELER_URL: '#'
      DATA_PROCESSOR_URL: '#'
      STARROCKS_URL: '#'
      AIRFLOW_URL: '#'

volumes:
  postgres_data:
