version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: django_app
    ports:
      - "80:8000"
    depends_on:
      - db
    restart: always
    environment:
      DJANGO_DEBUG: 'True'
      APPLICATION_HOST: '10.70.100.25'
      SSO_CLIENT_ID: '123456789fibr'
      SSO_CLIENT_SECRET: 'xn2TWEhX0Ker2h0ZEQXYLjE9SOIq1I24'
      SSO_REDIRECT_URI: 'http://10.70.100.25/callback/'
      SSO_BASE_URI: 'https://single.sysdev.id/'
      SSO_REALM_MASTER: 'single'
      HDFS_URL: "http://10.70.100.24:8088/"
      DASHBOARD_URL: 'http://10.70.100.24:5000/'
      DATA_MODELER_URL: 'http://10.70.100.8:7777/'
      DATA_PROCESSOR_URL: '#'
      STARROCKS_URL: "http://10.70.100.24:8035/"
      AIRFLOW_URL: "http://10.70.100.24:8089/"
      HELP_DESK_URL: "https://dev05.overtech.id/"
      HELP_DESK_MANAGEMENT_URL: "https://dev05.overtech.id/cms/admin/login"
      POSTGRESQL_HOST: "db"
      POSTGRESQL_PORT: "5432"
      POSTGRESQL_USER: "myuser"
      POSTGRESQL_PASSWORD: "mypassword"

volumes:
  postgres_data:
