# Generated by Django 4.2.13 on 2024-05-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="name",
            field=models.CharField(
                choices=[
                    ("admin_apps", "ADMIN APPS"),
                    ("dashboard", "Dashboard"),
                    ("airflow", "Airflow"),
                    ("data_modeler", "Data Modeler"),
                    ("data_processor", "Data Processor"),
                    ("starrocks", "Starrocks"),
                ],
                max_length=255,
                unique=True,
            ),
        ),
    ]
